```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(tidyverse)
library(GenomicRanges)
library(GenomicFeatures)
library(Homo.sapiens)
library(diffloop)
library(NMF)

#Specify file path here
path = ""
options(readr.num_columns = 0)

#CNA locations
loc = data.frame(read_delim(paste0(path, "index.txt"), 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = T))

#AR enhancers
talenh <- data.frame(read_delim(paste0(path, "AR_enh.txt"), 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = T))

#Unique interacting AR enhancers with promoters
enhloop <- data.frame(read_delim(paste0(path, "ARenh_loops.txt"), 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = T))
s_enhloop <- distinct(enhloop[,c(9,12:18)])
``` 

```{r helper functions, echo = FALSE}
geneRanges <- 
    function(db, column="ENTREZID")
{
    g <- genes(db, columns=column)
    col <- mcols(g)[[column]]
    genes <- granges(g)[rep(seq_along(g), elementNROWS(col))]
    mcols(genes)[[column]] <- as.character(unlist(col))
    genes
    }
```

```{r CNA at ranked ARBS}
#Two outputs: All ranked ARBS affected by LOSS and GAIN and all enhancers looping to promoter genes
result = vector(mode = "list")
gns <- geneRanges(Homo.sapiens, column="SYMBOL")
gns <- rmchr(gns)

for (i in loc$JK_index){
  #load patient cnv info, cleanup, remove REFs for speeding up computations 
  patcnv <- data.frame(read_delim(paste0(path, loc$path[i]), 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = F))

  colnames(patcnv) <- c("chr", "start", "end", "call", "val", "strd")
  patcnv <- patcnv[,-6]
  
  ##keep REF call for later gene whitelisting
  wlist <- patcnv[which(patcnv$call == "REF"),]
  patcnv <- patcnv[which(patcnv$call != "REF"),]
  
  gr_talenh = makeGRangesFromDataFrame(df= talenh, keep.extra.columns = T)
  grcnv = makeGRangesFromDataFrame(df= patcnv, keep.extra.columns = T)
  grcnv = rmchr(grcnv)
  
  overlaps <- findOverlaps(query = grcnv, subject = gr_talenh, type = "any")
  cnvenh <- data.frame(gr_talenh[subjectHits(overlaps),], grcnv[queryHits(overlaps),])
  cnvenh <- cnvenh[, c(-5:-6, -9:-13)]
  result[[i]] = cnvenh
}
result = do.call(rbind, result)

write_delim(result, path = paste0(path, "CNAenh.txt"), "\t", col_names = T) 
```

```{r clean up and get gains / loss per enh CNA}
test <- distinct(result[,5:7])
talenh_gain <- test[which(test$call == "GAIN"),]
talenh_loss <- test[which(test$call == "LOSS"),]

#Gains
gCNA_tal <- merge(talenh, talenh_gain, by.x = c("enhid", "ARtal"), by.y = c("enhid", "ARtal"), all = TRUE)
gCNA_tal[is.na(gCNA_tal)] <- 0
gCNA_tal$gain <- ifelse(gCNA_tal$call == "GAIN", 1, 0)

#Losses
lCNA_tal <- merge(talenh, talenh_loss, by.x = c("enhid", "ARtal"), by.y = c("enhid", "ARtal"), all = TRUE)
lCNA_tal[is.na(lCNA_tal)] <- 0
lCNA_tal$loss <- ifelse(lCNA_tal$call == "LOSS", 1, 0)

#Combine in dataframe
CNA_comb <- gCNA_tal[,c(1,8)]
CNA_comb$loss <- lCNA_tal[,8]
```
